### ISSUE TITLE
Disconnect

### ISSUE THREAD

**Issue by 3Lord3** [AlonsoAliaga/BetterRevive#4] opened 2020-12-18 05:59 UTC
**Describe the bug**
When a player bleeds, he can rejoin the server by breaking it. I have to kill the server process to make the console respond to commands.

**To Reproduce**
1. Make yourself bleed
2. Exit the server while bleeding
3. Log on to the server again
4. Check console

**Expected behavior**
The timer will continue, there will be no errors

**Important (please complete the following information):**
 - Java version: 11
 - Plugin version: 0.4-BETA
 - Server version: git-Paper-253 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Additional context**
![image](https://user-images.githubusercontent.com/62335161/102579893-e27f1f80-4116-11eb-90b8-ec18921914fd.png)
[latest.log](https://github.com/AlonsoAliaga/BetterRevive/files/5713940/latest.log)

**Comment by AlonsoAliaga** [comment] 2020-12-18 06:15
Hello, I just checked the log, I'll check the issue when I'm on PC.
About the expected behavior you wrote, no, this plugin does not save any data to make the player bleed again when joining. This plugin kills the player when they disconnect because he gives up and decide to disconnect.
This plugin won't save data to make player bleed again.
I'll check the error tomorrow, thanks for reporting

**Comment by AlonsoAliaga** [comment] 2020-12-18 22:56
Hello, can you join my discord server so I can send you a build for you to test it?
Join when you can https://alonsoaliaga.com/discord

**Comment by 3Lord3** [comment] 2020-12-19 08:07
Okay, I went into your discord. 3Lord3#4747

**Comment by AlonsoAliaga** [comment] 2020-12-26 13:58
Fixed in 0.5-BETA

**Closed as completed by AlonsoAliaga** 2020-12-26 13:58 UTC
Labels: (Resolution) Solved
